version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/backend/api/"
    reviewers:
      - "12rcu"
    commit-message:
      prefix: "[gradle dependency]"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "weekly"
      day: "friday"
  - package-ecosystem: "npm"
    directory: "/frontend/"
    reviewers:
      - "12rcu"
    commit-message:
      prefix: "[npm dependency]"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "weekly"
      day: "friday"