passphrase: 'test'
databases:
  sql:
    host: 'jdbc:mysql://localhost:3306/kma'
    user: 'root'
    password: 'test'
  sqlMigrate:
    host: 'jdbc:mysql://localhost:3306'
    user: 'root'
    password: 'test'
  kafka:
    host: 'xxx'
    port: 8083
    password: 'xxx'
  mqtt:
    host: '127.0.0.1'
    port: 1883
    clientId: 'kma'
    password: 'test'
    topic: '#'
  influx:
    host: 'xxx'
    port: 8086
    org: 'xxx'
    bucket: 'xxx'
    token: 'xxx'
pluginDirs: ["plugins"]