passphrase: 'xxx'
databases:
  sql:
    host: 'xxx'
    port: 3306
    schema: 'xxx'
    user: 'xxx'
    password: 'xxx'
  kafka:
    host: 'xxx'
    port: 8083
    password: 'xxx'
  mqtt:
    host: 'xxx'
    port: 1883
    clientId: 'xxx'
    topic: 'xxx'
pluginDirs: ["plugins"]