name: Backend Integration Test

on: [push]

jobs:
  integration:
    services:
      mysql:
        image: mysql:9
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: test
        options: >-
          --health-cmd "mysqladmin ping -ppass"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
      mqtt:
        image: eclipse-mosquitto:latest
        ports:
          - "1883:1883"
          - "9001:9001"
        volumes:
          - ./backend/mqtt:/mosquitto/config
          - ./backend/mqtt/mosquitto:/etc/mosquitto
        options: >-
          --health-cmd "mosquitto_pub -h localhost -p 1883 -t test -m 'health check' || exit 1"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: migrate
        run: mysql -u"root" -p"test" -h"127.0.0.1" --port=3306 < ./run/db-migration.sql
#      - name: copy mqtt config
#        run: docker cp ./mqtt/mosquitto.conf mqtt:/mosquitto/config/mosquitto.conf && docker cp ./mqtt/mosquitto mosquitto:/etc/mosquitto
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew :api:test
